my network: {
    icon: https://icons.terrastruct.com/infra%2F019-network.svg
}

my server: {
    icon: https://icons.terrastruct.com/aws%2F_General%2FTraditional-server_light-bg.svg
}

my network -> my server -> d2 logo

d2 logo {
    icon: ./d2-logo.png
}