direction: right
server -> github <- google

server: {
    shape: image
    icon: https://icons.terrastruct.com/tech%2F022-server.svg
}

github: {
    shape: image
    icon: https://icons.terrastruct.com/dev%2Fgithub.svg
}

google: {
    shape: image
    icon: ./google-logo-20250308.png
}