process1
server1.process1

server2
server2.process2

I'm a Parent.I'm a Child

apartment.Bedroom.Bathroom -> office.Spare Room.Bathroom: Portal

apartment.Bedroom -> process1

office.Spare Room <- server1.process1