imAShape: new cloud
im_a_shape.shape: diamond
im a shape
i'm a shape.shape: cloud
# notice that one-hyphen is not a connection
# whereas, `a--shape` would be a connection
a-shape
a -- a-shape

Database: SQLite {shape: cylinder}; Cassandra.shape:callout