shape: sequence_diagram
son -> father: Can I borrow your car?
friend -> father: Never lend your car to anyone\nwhom you have given birth.
father -> father: internal debate ensues
father -> son: sorry, not able to this time
son -> son: OK, I can ride a bike