shape: sequence_diagram
alice -> bob: What does it mean\nto be well-adjusted?
alice <- bob: The ability ot play bridge or\ngolf as if they were games. {
    style.stroke-dash: 2
}

alice.style.stroke: red
alice.style {
    stroke-dash: 0
}