my_code1: ||ts
    declare function getSmallPet(): Fish | Bird;
||

my_code2: |||ts
    declare function getSmallPet(): Fish | Bird;
    const works = (a > 1) || (b < 2)
|||

my_code3: |`ts
    declare function getSmallPet(): Fish | Bird;
    const works = (a > 1) || (b < 2)
`|

my_code1 -> my_code2 -> my_code3