poem_c: |md
    床前明月光，

    疑是地上霜。

    举头望明月，

    低头思故乡。
|

poem_e: |
    The moonlight shines brightly in front of my bed,
    
    I wonder if it is frost on the ground. 
    
    I look up at the moon,
    
    and think of my hometown.
|

poem_j: |
    ベッドの前で月明かりが明るく、
    
    地面に霜が
    
    降りているのかと思いました。
    
    明るい月を見上げながら故郷を想います。
|

poem_j <- poem_c -> poem_e